# Generated by Django 5.1.6 on 2025-02-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='unidad',
            field=models.CharField(choices=[('unidad', 'Unidad'), ('m', 'Metro'), ('m2', 'Metro cuadrado'), ('m3', 'Metro cúbico'), ('kg', 'Kilogramo'), ('ton', 'Tonelada'), ('litro', 'Litro'), ('saco', 'Saco')], default='unidad', max_length=20),
        ),
    ]
