# Generated by Django 5.1.6 on 2025-02-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0002_alter_material_unidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='cantidad_consumida',
            field=models.FloatField(default=0.0, help_text='Cantidad total de material consumido'),
        ),
        migrations.AddField(
            model_name='material',
            name='cantidad_pendiente',
            field=models.FloatField(default=0.0, help_text='Cantidad total de material pendiente'),
        ),
    ]
