# Generated by Django 5.1.6 on 2025-02-18 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CalculoMateriales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='Ejemplo: Muro Perimetral, Losa Segundo Nivel, Cimentación', max_length=200)),
                ('tipo_calculo', models.CharField(choices=[('muro', 'Muro'), ('losa_fundida', 'Losa Fundida'), ('losa_vigueta_bovedilla', 'Losa con Vigueta y Bovedilla'), ('losa_acero', 'Losa de Acero'), ('cimentacion', 'Cimentación')], max_length=50)),
                ('area', models.FloatField(help_text='Área en metros cuadrados')),
                ('desperdicio', models.FloatField(default=5.0, help_text='Porcentaje de desperdicio')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculos', to='calculos.proyecto')),
            ],
        ),
    ]
