# Generated by Django 5.1.6 on 2025-02-18 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculomateriales',
            name='descripcion',
            field=models.CharField(default='Sin descripción', help_text='Ejemplo: Muro Perimetral, Losa Segundo Nivel, Cimentación', max_length=200),
        ),
    ]
