# Generated by Django 5.1.6 on 2025-02-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculos', '0002_alter_calculomateriales_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculomateriales',
            name='avance',
            field=models.FloatField(default=0.0, help_text='Porcentaje de avance de la obra'),
        ),
    ]
