# Generated by Django 5.1.6 on 2025-02-20 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculos', '0003_calculomateriales_avance'),
        ('materiales', '0003_material_cantidad_consumida_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculoMaterialDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_requerida', models.FloatField()),
                ('cantidad_consumida', models.FloatField(default=0.0)),
                ('cantidad_pendiente', models.FloatField()),
                ('calculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='calculos.calculomateriales')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiales.material')),
            ],
        ),
    ]
