# Generated by Django 5.1.6 on 2025-02-24 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculos', '0005_alter_calculomateriales_tipo_calculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTrabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('tarifa_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tarifa_ml', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tarifa_dia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='calculomateriales',
            name='avance',
        ),
        migrations.AddField(
            model_name='calculomateriales',
            name='cantidad',
            field=models.FloatField(blank=True, help_text='Cantidad en metros lineales o unidades', null=True),
        ),
        migrations.AlterField(
            model_name='calculomateriales',
            name='area',
            field=models.FloatField(blank=True, help_text='Área en metros cuadrados', null=True),
        ),
        migrations.AlterField(
            model_name='calculomateriales',
            name='descripcion',
            field=models.CharField(default='Sin descripción', help_text='Ejemplo: Cimentación Principal, Zapatas de Esquina, etc.', max_length=200),
        ),
        migrations.AlterField(
            model_name='calculomateriales',
            name='tipo_calculo',
            field=models.CharField(choices=[('cimiento_corrido_1', 'Cimiento Corrido Tipo 1'), ('cimiento_corrido_2', 'Cimiento Corrido Tipo 2'), ('zapata_1', 'Zapata Tipo 1'), ('zapata_2', 'Zapata Tipo 2'), ('muro', 'Muro'), ('losa_fundida', 'Losa Fundida'), ('losa_vigueta_bovedilla', 'Losa con Vigueta y Bovedilla'), ('losa_acero', 'Losa de Acero'), ('vigas_confinamiento', 'Vigas de Confinamiento'), ('escaleras', 'Escaleras'), ('piso', 'Piso Cerámico'), ('cielo_falso', 'Cielo Falso'), ('C-A', 'Columna Tipo A'), ('C-B', 'Columna Tipo B'), ('C-C', 'Columna Tipo C'), ('C-D', 'Columna Tipo D')], max_length=50),
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculos.tipotrabajador')),
            ],
        ),
    ]
